package config

// Config is auro generated by https://xuri.me/toml-to-go/
type Config struct {
	Title    string `toml:"title"`
	Database struct {
		SocketFile   string `toml:"socket_file"`
		Server       string `toml:"server"`
		Port         string `toml:"port"`
		User         string `toml:"user"`
		Password     string `toml:"password"`
		DbName       string `toml:"db_name"`
		MaxIdleConns int    `toml:"max_idle_conns"`
	} `toml:"database"`
}
