// This file is generated by SQLBoiler (https://github.com/volatiletech/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package model

var TableNames = struct {
	Points  string
	Rooms   string
	Strokes string
	Tokens  string
}{
	Points:  "points",
	Rooms:   "rooms",
	Strokes: "strokes",
	Tokens:  "tokens",
}
